### ISSUE TITLE
How is your platform-agnostic ultimate OS progress

### ISSUE THREAD

**Issue by Moanrisy** [akhramov/akhramov.github.io#1]
Maybe you can share what is your emacs capability as platform-agnostic ultimate OS after 2 years :)

**Comment by akhramov** [comment]
Yeah, this owes an update.

New years resolutions are meant to fail, yet I accomplished something. 

For instance, my [emacs config](https://github.com/akhramov/emacs.d) is now in LP style.

I don't use tmux anymore, but not because I found a viable replacement. I adjusted my workflows, and now projectile fits me well.

Email clients. That's a tough one. I had set mu4e up, but was too lazy to get used to it. So, Thunderbird it is.


Oh have I failed
